
CREATE TABLE IF NOT EXISTS public.data(
    CUSTOMER_ID INTEGER,
    GENRE VARCHAR(6),
    AGE INTEGER,
    ANNUAL_INCOME INTEGER,  
    SPENDING_SCORE INTEGER, 
    CITY_NAME VARCHAR(21), 
    CITY_LATITUDE DECIMAL(8,6),
    CITY_LONGITUDE DECIMAL(9,6),
    COUNTRY_CODE VARCHAR(3),
    CITY_POPULATION INTEGER,  
    IS_CAPITAL BOOL,
    PRODUCT_NAME VARCHAR(110), 
    PRODUCT_BRAND VARCHAR(20), 
    PRODUCT_RATING INTEGER,
    PRODUCT_PRICE FLOAT,
    COUNTRY_NAME VARCHAR(20),
    DATE DATE
);



