
-- Dimension Date
CREATE TABLE dim_date(
    DATE_KEY INTEGER NOT NULL,
    DATE DATE NOT NULL,
    WEEKDAY VARCHAR(9) NOT NULL,
    WEEKDAY_NUM INTEGER NOT NULL,
    DAY_MONTH INTEGER NOT NULL,
    DAY_OF_YEAR INTEGER NOT NULL,
    WEEK_OF_YEAR INTEGER NOT NULL,
    ISO_WEEK CHAR(10) NOT NULL,
    MONTH_NUM INTEGER NOT NULL,
    MONTH_NAME VARCHAR(9) NOT NULL,
    MONTH_NAME_SHORT CHAR(3) NOT NULL,
    QUARTER INTEGER NOT NULL,
    YEAR INTEGER NOT NULL,
    FIRST_DAY_OF_MONTH DATE NOT NULL,
    LAST_DAY_OF_MONTH DATE NOT NULL,
    YYYYMM CHAR(7) NOT NULL,
    WEEKEND_INDR CHAR(10) NOT NULL
);

ALTER TABLE dim_date
ADD PRIMARY KEY (date_key);


INSERT INTO dim_date
SELECT TO_CHAR(datum, 'yyyymmdd')::INT AS DATE_KEY,
datum AS DATE,
TO_CHAR(datum, 'TMDay') AS WEEKDAY,
EXTRACT(ISODOW FROM datum) AS WEEKDAY_NUM,
EXTRACT(DAY FROM datum) AS DAY_MONTH,
EXTRACT(DOY FROM datum) AS DAY_OF_YEAR,
EXTRACT(WEEK FROM datum) AS WEEK_OF_YEAR,
EXTRACT(ISOYEAR FROM datum) || TO_CHAR(datum, '"-W"IW-') || EXTRACT(ISODOW FROM datum) AS ISO_WEEK,
EXTRACT(MONTH FROM datum) AS MONTH,
TO_CHAR(datum, 'TMMonth') AS MONTH_NAME,
TO_CHAR(datum, 'Mon') AS MONTH_NAME_SHORT,
EXTRACT(QUARTER FROM datum) AS QUARTER,
EXTRACT(YEAR FROM datum) AS YEAR,
datum + (1 - EXTRACT(DAY FROM datum))::INT AS FIRST_DAY_OF_MONTH,
(DATE_TRUNC('MONTH', datum) + INTERVAL '1 MONTH - 1 day')::DATE AS LAST_DAY_OF_MONTH,
CONCAT(TO_CHAR(datum, 'yyyy'),'-',TO_CHAR(datum, 'mm')) AS MMYYYY,
CASE
   WHEN EXTRACT(ISODOW FROM datum) IN (6, 7) THEN 'weekend'
   ELSE 'weekday'
   END AS WEEKEND_INDR
FROM (SELECT '2021-01-01'::DATE + SEQUENCE.DAY AS datum
      FROM GENERATE_SERIES(0, 365) AS SEQUENCE (DAY)
      GROUP BY SEQUENCE.DAY) DQ
ORDER BY 1;
-- Dimension Date



-- Dimension Customer
SELECT DISTINCT CUSTOMER_ID 
INTO customers
FROM data;

CREATE TABLE IF NOT EXISTS dim_customer AS
SELECT d.CUSTOMER_ID, 
       d.GENRE, 
       d.AGE, 
       d.ANNUAL_INCOME, 
       d.SPENDING_SCORE
FROM data AS d
LEFT JOIN customers AS c
ON d.CUSTOMER_ID = c.CUSTOMER_ID;

ALTER TABLE dim_customer
ADD PRIMARY KEY (CUSTOMER_ID);

DROP TABLE customers;
-- Dimension Customer



-- Dimension City
SELECT DISTINCT CITY_NAME 
INTO cities
FROM data;

CREATE TABLE IF NOT EXISTS dim_city AS
SELECT row_number() over (order by d.CITY_NAME) AS CITY_ID, 
    d.CITY_NAME, 
    d.CITY_LATITUDE, 
    d.CITY_LONGITUDE, 
    d.COUNTRY_CODE, 
    d.COUNTRY_NAME, 
    d.IS_CAPITAL
FROM data AS d
LEFT JOIN cities AS c
ON d.CITY_NAME = c.CITY_NAME;

ALTER TABLE dim_city
ADD PRIMARY KEY (CITY_ID);

DROP TABLE cities;
-- Dimension City



-- Dimension Product
SELECT DISTINCT PRODUCT_NAME 
INTO products
FROM data;

CREATE TABLE IF NOT EXISTS dim_product AS
SELECT row_number() over (order by d.PRODUCT_NAME) AS PRODUCT_ID, 
    d.PRODUCT_NAME, 
    d.PRODUCT_BRAND, 
    d.PRODUCT_RATING
FROM data AS d
LEFT JOIN products AS p
ON d.PRODUCT_NAME = p.PRODUCT_NAME;

ALTER TABLE dim_product
ADD PRIMARY KEY (PRODUCT_ID);

DROP TABLE products;
-- Dimension Product



-- Fact Table
CREATE TABLE IF NOT EXISTS fact_sales_temp AS
SELECT dim_d.DATE_KEY, 
       dim_c.CUSTOMER_ID, 
       dim_ci.CITY_ID, 
       dim_p.PRODUCT_ID, 
       d.PRODUCT_PRICE AS PRICE
FROM data AS d
LEFT JOIN dim_date AS dim_d ON d.DATE = dim_d.DATE
LEFT JOIN dim_customer AS dim_c ON d.CUSTOMER_ID = dim_c.CUSTOMER_ID
LEFT JOIN dim_city AS dim_ci ON d.CITY_NAME = dim_ci.CITY_NAME
LEFT JOIN dim_product AS dim_p ON d.PRODUCT_NAME = dim_p.PRODUCT_NAME;

SELECT row_number() over (order by DATE_KEY) as SALES_ID, * 
into fact_sales
from fact_sales_temp;

DROP TABLE fact_sales_temp
-- Fact Table




